version: "2"
services:
  bracket-picker:
    image: amcolash/bracket-picker
    build: ./
    container_name: bracket-picker
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PHOTO_DIR}:/photos
      - ./tmp:/tmp/bracket-picker
    network_mode: "host"
    entrypoint: node /usr/src/app/index.js /photos
    env_file:
      - .env
    environment:
      - NODE_ENV=production
